name: Format

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          # Recommended: latest versions of Google Java Format require JDK 11+
          java-version: "11"
      - name: Google Java Format
        uses: axel-op/googlejavaformat-action@v3.4.0
